val qtrs = spark.read.parquet("s3a://loan-performance-data/qtr_acquisition_table").select($"qtr").distinct.collect

def id_join(qtr:String) = {
  val perf = spark.read.parquet("s3a://loan-performance-data/performance_table/qtr="+qtr).drop("qtr")
  val acq = spark.read.parquet("s3a://loan-performance-data/acquisition_table/qtr="+qtr).drop("qtr")
  val joined = perf.join(acq,"LOAN_IDENTIFIER")
  qtr = qtr.replace(".parquet", "")
  joined.write.parquet("s3a://loan-performance-data/full_data/qtr="+qtr)
}

import scala.collection.parallel._
parqtr = qtrs.par
parqtr.tasksupport = new ForkJoinTaskSupport(new scala.concurrent.forkjoin.ForkJoinPool(8))

|-- LOAN_IDENTIFIER: string (nullable = true)
|-- MONTHLY_REPORTING: string (nullable = true)
|-- SERVICER_NAME: string (nullable = true)
|-- CURRENT_INTEREST_RATE: double (nullable = true)
|-- CURRENT_ACTUAL_UPB: double (nullable = true)
|-- LOAN_AGE: double (nullable = true)
|-- REMAINING_MONTHS_TO_LEGAL_MATURITY: double (nullable = true)
|-- ADJUSTED_MONTHS_TO_MATURITY: double (nullable = true)
|-- MATURITY_DATE: string (nullable = true)
|-- METROPOLITAN_STATISTICAL_AREA: double (nullable = true)
|-- CURRENT_LOAN_DELINQUENCY_STATUS: string (nullable = true)
|-- MODIFICATION_FLAG: string (nullable = true)
|-- ZERO_BALANCE_CODE: string (nullable = true)
|-- ZERO_BALANCE_EFFECTIVE_DATE: string (nullable = true)
|-- LAST_PAID_INSTALLMENT_DATE: string (nullable = true)
|-- FORECLOSURE_DATE: string (nullable = true)
|-- DISPOSITION_DATE: string (nullable = true)
|-- FORECLOSURE_COSTS: double (nullable = true)
|-- PROPERTY_PRESERVATION_AND_REPAIR_COSTS: double (nullable = true)
|-- ASSET_RECOVERY_COSTS: double (nullable = true)
|-- MISCELLANEOUS_HOLDING_EXPENSES_AND_CREDITS: double (nullable = true)
|-- ASSOCIATED_TAXES_FOR_HOLDING_PROPERTY: double (nullable = true)
|-- NET_SALE_PROCEEDS: double (nullable = true)
|-- CREDIT_ENHANCEMENT_PROCEEDS: double (nullable = true)
|-- REPURCHASE_MAKE_WHOLE_PROCEEDS: double (nullable = true)
|-- OTHER_FORECLOSURE_PROCEEDS: double (nullable = true)
|-- NON_INTEREST_BEARING_UPB: double (nullable = true)
|-- PRINCIPAL_FORGIVENESS_AMOUNT: double (nullable = true)
|-- REPURCHASE_MAKE_WHOLE_PROCEEDS_FLAG: string (nullable = true)
|-- FORECLOSURE_PRINCIPAL_WRITE_OFF_AMOUNT: double (nullable = true)
|-- SERVICING_ACTIVITY_INDICATOR: string (nullable = true)
|-- ORIGINATION_CHANNEL: string (nullable = true)
|-- SELLER_NAME: string (nullable = true)
|-- ORIGINAL_INTEREST_RATE: double (nullable = true)
|-- ORIGINAL_UPB: double (nullable = true)
|-- ORIGINAL_LOAN_TERM: double (nullable = true)
|-- ORIGINATION_DATE: string (nullable = true)
|-- FIRST_PAYMENT_DATE: string (nullable = true)
|-- ORIGINAL_LOAN-TO-VALUE: double (nullable = true)
|-- ORIGINAL_COMBINED_LOAN-TO-VALUE: double (nullable = true)
|-- NUMBER_OF_BORROWERS: double (nullable = true)
|-- ORIGINAL_DEBT_TO_INCOME_RATIO: double (nullable = true)
|-- BORROWER_CREDIT_SCORE_AT_ORIGINATION: double (nullable = true)
|-- FIRST_TIME_HOME_BUYER_INDICATOR: string (nullable = true)
|-- LOAN_PURPOSE: string (nullable = true)
|-- PROPERTY_TYPE: string (nullable = true)
|-- NUMBER_OF_UNITS: string (nullable = true)
|-- OCCUPANCY_TYPE: string (nullable = true)
|-- PROPERTY_STATE: string (nullable = true)
|-- ZIP_CODE_SHORT: string (nullable = true)
|-- PRIMARY_MORTGAGE_INSURANCE_PERCENT: double (nullable = true)
|-- PRODUCT_TYPE: string (nullable = true)
|-- CO-BORROWER_CREDIT_SCORE_AT_ORIGINATION: double (nullable = true)
|-- MORTGAGE_INSURANCE_TYPE: double (nullable = true)
|-- RELOCATION_MORTGAGE_INDICATOR: string (nullable = true)
